files:
  test_data: t10k-images-idx3-ubyte.gz
  test_labels: t10k-labels-idx1-ubyte.gz
  train_data: train-images-idx3-ubyte.gz
  train_labels: train-labels-idx1-ubyte.gz
paths:
  data_dir: ${hydra:runtime.cwd}/data
  log_path: ./runs
params:
  epoch_count: 20
  lr: 5e-5
  batch_size: 128